site_name: Albert S. Dias
site_description: Site pessoal para textos, notas, apostilas e artigos
site_author: Albert S. Dias

theme:
  name: material
  language: pt-BR
  palette:
    scheme: slate
    primary: blue
    accent: light blue

nav:
  - Início: index.md
  - Textos:
      - Lista: textos.md
      - Pasta: Textos/
  - Apostilas: apostilas.md
  - Relatórios: relatorios.md
  - Artigos: artigos.md
  - Materiais: material.md
