site_name: albertdias.github.io
site_description: Site para textos pessoais, notas de estudo e apostilas
site_author: Albert Dias

theme:
  name: material
  language: pt-BR
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - header.autohide
    - content.code.copy

nav:
  - Início: index.md
  - Textos: textos/index.md
  - Artigos: artigos/index.md
  - Apostilas: apostilas/index.md
  - Relatórios: relatorios/index.md
  - Materiais: materiais/index.md
  - Posts: posts/index.md
