site_name: Albert S. Dias
site_description: Site pessoal para textos, notas, apostilas e artigos
site_author: Albert S. Dias

theme:
  name: material
  palette:
    - scheme: slate
      primary: black
      accent: blue
  features:
    - navigation.expand
    - navigation.instant
    - navigation.sections
    - navigation.footer

nav:
  - Início: index.md
  - Sobre mim: sobre/index.md
  - Textos:
      - Lista: textos.md
      - Pasta: Textos/
  - Apostilas: apostilas.md
  - Relatórios: relatorios.md
  - Artigos: artigos.md
  - Materiais: material.md
